syntax = "proto3";

package auth;

import "google/protobuf/timestamp.proto";

option go_package = "/auth";

message AuthUser {
    string username = 1;
    string email = 2;
    string password = 3;
}

message RefreshToken {
    string token = 1;
    google.protobuf.Timestamp start_TTL = 2;
    google.protobuf.Timestamp end_TTL = 3;
    string user_ID = 4;
}

message AccessToken {
    string token = 1;
    google.protobuf.Timestamp start_TTL = 2;
    google.protobuf.Timestamp end_TTL = 3;
    string user_ID = 4;
}

message UserSession {
    string ID = 1;
    string user_agent = 2;
    string IP = 3;
    google.protobuf.Timestamp created_at = 4;
    google.protobuf.Timestamp last_active_at = 5;
    bool current = 6;
}

message UserSessions {
    repeated UserSession user_sessions = 1;
}

message Tokens {
    RefreshToken refresh_token = 1;
    AccessToken access_token = 2;
}

message Success {
    bool success = 1;
}

service AuthService {
    rpc Login (AuthUser) returns (Tokens) {};
    rpc Refresh (RefreshToken) returns (Tokens) {};
    rpc Logout (RefreshToken) returns (Success) {};
    rpc LogoutAll (RefreshToken) returns (Success) {};
    rpc GetUserSessions (RefreshToken) returns (UserSessions) {};
}
