// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.26.1
// source: access.proto

package access

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AccessService_CreateRole_FullMethodName               = "/access.AccessService/CreateRole"
	AccessService_GetRole_FullMethodName                  = "/access.AccessService/GetRole"
	AccessService_CreatePermission_FullMethodName         = "/access.AccessService/CreatePermission"
	AccessService_GetPermissionsByUserID_FullMethodName   = "/access.AccessService/GetPermissionsByUserID"
	AccessService_GetPermissionsByRoleName_FullMethodName = "/access.AccessService/GetPermissionsByRoleName"
)

// AccessServiceClient is the client API for AccessService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AccessServiceClient interface {
	CreateRole(ctx context.Context, in *Role, opts ...grpc.CallOption) (*Success, error)
	GetRole(ctx context.Context, in *UserID, opts ...grpc.CallOption) (*Role, error)
	CreatePermission(ctx context.Context, in *PermissionReq, opts ...grpc.CallOption) (*Success, error)
	GetPermissionsByUserID(ctx context.Context, in *UserID, opts ...grpc.CallOption) (*Permissions, error)
	GetPermissionsByRoleName(ctx context.Context, in *RoleName, opts ...grpc.CallOption) (*Permissions, error)
}

type accessServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAccessServiceClient(cc grpc.ClientConnInterface) AccessServiceClient {
	return &accessServiceClient{cc}
}

func (c *accessServiceClient) CreateRole(ctx context.Context, in *Role, opts ...grpc.CallOption) (*Success, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Success)
	err := c.cc.Invoke(ctx, AccessService_CreateRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessServiceClient) GetRole(ctx context.Context, in *UserID, opts ...grpc.CallOption) (*Role, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Role)
	err := c.cc.Invoke(ctx, AccessService_GetRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessServiceClient) CreatePermission(ctx context.Context, in *PermissionReq, opts ...grpc.CallOption) (*Success, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Success)
	err := c.cc.Invoke(ctx, AccessService_CreatePermission_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessServiceClient) GetPermissionsByUserID(ctx context.Context, in *UserID, opts ...grpc.CallOption) (*Permissions, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Permissions)
	err := c.cc.Invoke(ctx, AccessService_GetPermissionsByUserID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessServiceClient) GetPermissionsByRoleName(ctx context.Context, in *RoleName, opts ...grpc.CallOption) (*Permissions, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Permissions)
	err := c.cc.Invoke(ctx, AccessService_GetPermissionsByRoleName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccessServiceServer is the server API for AccessService service.
// All implementations must embed UnimplementedAccessServiceServer
// for forward compatibility.
type AccessServiceServer interface {
	CreateRole(context.Context, *Role) (*Success, error)
	GetRole(context.Context, *UserID) (*Role, error)
	CreatePermission(context.Context, *PermissionReq) (*Success, error)
	GetPermissionsByUserID(context.Context, *UserID) (*Permissions, error)
	GetPermissionsByRoleName(context.Context, *RoleName) (*Permissions, error)
	mustEmbedUnimplementedAccessServiceServer()
}

// UnimplementedAccessServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAccessServiceServer struct{}

func (UnimplementedAccessServiceServer) CreateRole(context.Context, *Role) (*Success, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRole not implemented")
}
func (UnimplementedAccessServiceServer) GetRole(context.Context, *UserID) (*Role, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRole not implemented")
}
func (UnimplementedAccessServiceServer) CreatePermission(context.Context, *PermissionReq) (*Success, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePermission not implemented")
}
func (UnimplementedAccessServiceServer) GetPermissionsByUserID(context.Context, *UserID) (*Permissions, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPermissionsByUserID not implemented")
}
func (UnimplementedAccessServiceServer) GetPermissionsByRoleName(context.Context, *RoleName) (*Permissions, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPermissionsByRoleName not implemented")
}
func (UnimplementedAccessServiceServer) mustEmbedUnimplementedAccessServiceServer() {}
func (UnimplementedAccessServiceServer) testEmbeddedByValue()                       {}

// UnsafeAccessServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AccessServiceServer will
// result in compilation errors.
type UnsafeAccessServiceServer interface {
	mustEmbedUnimplementedAccessServiceServer()
}

func RegisterAccessServiceServer(s grpc.ServiceRegistrar, srv AccessServiceServer) {
	// If the following call pancis, it indicates UnimplementedAccessServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AccessService_ServiceDesc, srv)
}

func _AccessService_CreateRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Role)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessServiceServer).CreateRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessService_CreateRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessServiceServer).CreateRole(ctx, req.(*Role))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessService_GetRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessServiceServer).GetRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessService_GetRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessServiceServer).GetRole(ctx, req.(*UserID))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessService_CreatePermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PermissionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessServiceServer).CreatePermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessService_CreatePermission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessServiceServer).CreatePermission(ctx, req.(*PermissionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessService_GetPermissionsByUserID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessServiceServer).GetPermissionsByUserID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessService_GetPermissionsByUserID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessServiceServer).GetPermissionsByUserID(ctx, req.(*UserID))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessService_GetPermissionsByRoleName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoleName)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessServiceServer).GetPermissionsByRoleName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessService_GetPermissionsByRoleName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessServiceServer).GetPermissionsByRoleName(ctx, req.(*RoleName))
	}
	return interceptor(ctx, in, info, handler)
}

// AccessService_ServiceDesc is the grpc.ServiceDesc for AccessService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AccessService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "access.AccessService",
	HandlerType: (*AccessServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRole",
			Handler:    _AccessService_CreateRole_Handler,
		},
		{
			MethodName: "GetRole",
			Handler:    _AccessService_GetRole_Handler,
		},
		{
			MethodName: "CreatePermission",
			Handler:    _AccessService_CreatePermission_Handler,
		},
		{
			MethodName: "GetPermissionsByUserID",
			Handler:    _AccessService_GetPermissionsByUserID_Handler,
		},
		{
			MethodName: "GetPermissionsByRoleName",
			Handler:    _AccessService_GetPermissionsByRoleName_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "access.proto",
}
