// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.26.1
// source: access.proto

package access

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Role struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	IsDefault     bool                   `protobuf:"varint,4,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Role) Reset() {
	*x = Role{}
	mi := &file_access_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Role) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Role) ProtoMessage() {}

func (x *Role) ProtoReflect() protoreflect.Message {
	mi := &file_access_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Role.ProtoReflect.Descriptor instead.
func (*Role) Descriptor() ([]byte, []int) {
	return file_access_proto_rawDescGZIP(), []int{0}
}

func (x *Role) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Role) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Role) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Role) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

func (x *Role) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Role) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Permission struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	IsDefault     bool                   `protobuf:"varint,4,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Permission) Reset() {
	*x = Permission{}
	mi := &file_access_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Permission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Permission) ProtoMessage() {}

func (x *Permission) ProtoReflect() protoreflect.Message {
	mi := &file_access_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Permission.ProtoReflect.Descriptor instead.
func (*Permission) Descriptor() ([]byte, []int) {
	return file_access_proto_rawDescGZIP(), []int{1}
}

func (x *Permission) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Permission) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Permission) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Permission) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

func (x *Permission) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Permission) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type PermissionReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleName      string                 `protobuf:"bytes,1,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	Permission    *Permission            `protobuf:"bytes,2,opt,name=Permission,proto3" json:"Permission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermissionReq) Reset() {
	*x = PermissionReq{}
	mi := &file_access_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionReq) ProtoMessage() {}

func (x *PermissionReq) ProtoReflect() protoreflect.Message {
	mi := &file_access_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionReq.ProtoReflect.Descriptor instead.
func (*PermissionReq) Descriptor() ([]byte, []int) {
	return file_access_proto_rawDescGZIP(), []int{2}
}

func (x *PermissionReq) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *PermissionReq) GetPermission() *Permission {
	if x != nil {
		return x.Permission
	}
	return nil
}

type UpdateUserRoleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User_ID       string                 `protobuf:"bytes,1,opt,name=user_ID,json=userID,proto3" json:"user_ID,omitempty"`
	OldRoleName   string                 `protobuf:"bytes,2,opt,name=old_role_name,json=oldRoleName,proto3" json:"old_role_name,omitempty"`
	NewRoleName   string                 `protobuf:"bytes,3,opt,name=new_role_name,json=newRoleName,proto3" json:"new_role_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRoleReq) Reset() {
	*x = UpdateUserRoleReq{}
	mi := &file_access_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRoleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRoleReq) ProtoMessage() {}

func (x *UpdateUserRoleReq) ProtoReflect() protoreflect.Message {
	mi := &file_access_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRoleReq.ProtoReflect.Descriptor instead.
func (*UpdateUserRoleReq) Descriptor() ([]byte, []int) {
	return file_access_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateUserRoleReq) GetUser_ID() string {
	if x != nil {
		return x.User_ID
	}
	return ""
}

func (x *UpdateUserRoleReq) GetOldRoleName() string {
	if x != nil {
		return x.OldRoleName
	}
	return ""
}

func (x *UpdateUserRoleReq) GetNewRoleName() string {
	if x != nil {
		return x.NewRoleName
	}
	return ""
}

type UserIDRoleName struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User_ID       string                 `protobuf:"bytes,1,opt,name=user_ID,json=userID,proto3" json:"user_ID,omitempty"`
	RoleName      string                 `protobuf:"bytes,2,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserIDRoleName) Reset() {
	*x = UserIDRoleName{}
	mi := &file_access_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserIDRoleName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserIDRoleName) ProtoMessage() {}

func (x *UserIDRoleName) ProtoReflect() protoreflect.Message {
	mi := &file_access_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserIDRoleName.ProtoReflect.Descriptor instead.
func (*UserIDRoleName) Descriptor() ([]byte, []int) {
	return file_access_proto_rawDescGZIP(), []int{4}
}

func (x *UserIDRoleName) GetUser_ID() string {
	if x != nil {
		return x.User_ID
	}
	return ""
}

func (x *UserIDRoleName) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

type Roles struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Roles         []*Role                `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Roles) Reset() {
	*x = Roles{}
	mi := &file_access_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Roles) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Roles) ProtoMessage() {}

func (x *Roles) ProtoReflect() protoreflect.Message {
	mi := &file_access_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Roles.ProtoReflect.Descriptor instead.
func (*Roles) Descriptor() ([]byte, []int) {
	return file_access_proto_rawDescGZIP(), []int{5}
}

func (x *Roles) GetRoles() []*Role {
	if x != nil {
		return x.Roles
	}
	return nil
}

type Permissions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Permissions   []*Permission          `protobuf:"bytes,1,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Permissions) Reset() {
	*x = Permissions{}
	mi := &file_access_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Permissions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Permissions) ProtoMessage() {}

func (x *Permissions) ProtoReflect() protoreflect.Message {
	mi := &file_access_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Permissions.ProtoReflect.Descriptor instead.
func (*Permissions) Descriptor() ([]byte, []int) {
	return file_access_proto_rawDescGZIP(), []int{6}
}

func (x *Permissions) GetPermissions() []*Permission {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type FullPermissions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Permissions   []string               `protobuf:"bytes,1,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FullPermissions) Reset() {
	*x = FullPermissions{}
	mi := &file_access_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FullPermissions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FullPermissions) ProtoMessage() {}

func (x *FullPermissions) ProtoReflect() protoreflect.Message {
	mi := &file_access_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FullPermissions.ProtoReflect.Descriptor instead.
func (*FullPermissions) Descriptor() ([]byte, []int) {
	return file_access_proto_rawDescGZIP(), []int{7}
}

func (x *FullPermissions) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type UserID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User_ID       string                 `protobuf:"bytes,1,opt,name=user_ID,json=userID,proto3" json:"user_ID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserID) Reset() {
	*x = UserID{}
	mi := &file_access_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserID) ProtoMessage() {}

func (x *UserID) ProtoReflect() protoreflect.Message {
	mi := &file_access_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserID.ProtoReflect.Descriptor instead.
func (*UserID) Descriptor() ([]byte, []int) {
	return file_access_proto_rawDescGZIP(), []int{8}
}

func (x *UserID) GetUser_ID() string {
	if x != nil {
		return x.User_ID
	}
	return ""
}

type RoleName struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleName      string                 `protobuf:"bytes,1,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleName) Reset() {
	*x = RoleName{}
	mi := &file_access_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleName) ProtoMessage() {}

func (x *RoleName) ProtoReflect() protoreflect.Message {
	mi := &file_access_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleName.ProtoReflect.Descriptor instead.
func (*RoleName) Descriptor() ([]byte, []int) {
	return file_access_proto_rawDescGZIP(), []int{9}
}

func (x *RoleName) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

type Success struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Success) Reset() {
	*x = Success{}
	mi := &file_access_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Success) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Success) ProtoMessage() {}

func (x *Success) ProtoReflect() protoreflect.Message {
	mi := &file_access_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Success.ProtoReflect.Descriptor instead.
func (*Success) Descriptor() ([]byte, []int) {
	return file_access_proto_rawDescGZIP(), []int{10}
}

func (x *Success) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_access_proto protoreflect.FileDescriptor

const file_access_proto_rawDesc = "" +
	"\n" +
	"\faccess.proto\x12\x06access\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe1\x01\n" +
	"\x04Role\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"is_default\x18\x04 \x01(\bR\tisDefault\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xe7\x01\n" +
	"\n" +
	"Permission\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"is_default\x18\x04 \x01(\bR\tisDefault\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"`\n" +
	"\rPermissionReq\x12\x1b\n" +
	"\trole_name\x18\x01 \x01(\tR\broleName\x122\n" +
	"\n" +
	"Permission\x18\x02 \x01(\v2\x12.access.PermissionR\n" +
	"Permission\"t\n" +
	"\x11UpdateUserRoleReq\x12\x17\n" +
	"\auser_ID\x18\x01 \x01(\tR\x06userID\x12\"\n" +
	"\rold_role_name\x18\x02 \x01(\tR\voldRoleName\x12\"\n" +
	"\rnew_role_name\x18\x03 \x01(\tR\vnewRoleName\"F\n" +
	"\x0eUserIDRoleName\x12\x17\n" +
	"\auser_ID\x18\x01 \x01(\tR\x06userID\x12\x1b\n" +
	"\trole_name\x18\x02 \x01(\tR\broleName\"+\n" +
	"\x05Roles\x12\"\n" +
	"\x05roles\x18\x01 \x03(\v2\f.access.RoleR\x05roles\"C\n" +
	"\vPermissions\x124\n" +
	"\vpermissions\x18\x01 \x03(\v2\x12.access.PermissionR\vpermissions\"3\n" +
	"\x0fFullPermissions\x12 \n" +
	"\vpermissions\x18\x01 \x03(\tR\vpermissions\"!\n" +
	"\x06UserID\x12\x17\n" +
	"\auser_ID\x18\x01 \x01(\tR\x06userID\"'\n" +
	"\bRoleName\x12\x1b\n" +
	"\trole_name\x18\x01 \x01(\tR\broleName\"#\n" +
	"\aSuccess\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xda\x04\n" +
	"\rAccessService\x12-\n" +
	"\n" +
	"CreateRole\x12\f.access.Role\x1a\x0f.access.Success\"\x00\x12+\n" +
	"\bGetRoles\x12\x0e.access.UserID\x1a\r.access.Roles\"\x00\x12<\n" +
	"\x10CreatePermission\x12\x15.access.PermissionReq\x1a\x0f.access.Success\"\x00\x12>\n" +
	"\x11GetFullPermission\x12\x0e.access.UserID\x1a\x17.access.FullPermissions\"\x00\x12?\n" +
	"\x16GetPermissionsByUserID\x12\x0e.access.UserID\x1a\x13.access.Permissions\"\x00\x12C\n" +
	"\x18GetPermissionsByRoleName\x12\x10.access.RoleName\x1a\x13.access.Permissions\"\x00\x128\n" +
	"\vAddUserRole\x12\x16.access.UserIDRoleName\x1a\x0f.access.Success\"\x00\x121\n" +
	"\fBindUserRole\x12\x0e.access.UserID\x1a\x0f.access.Success\"\x00\x12?\n" +
	"\x0fReplaceUserRole\x12\x19.access.UpdateUserRoleReq\x1a\x0f.access.Success\"\x00\x12;\n" +
	"\x0eDeleteUserRole\x12\x16.access.UserIDRoleName\x1a\x0f.access.Success\"\x00B\tZ\a/accessb\x06proto3"

var (
	file_access_proto_rawDescOnce sync.Once
	file_access_proto_rawDescData []byte
)

func file_access_proto_rawDescGZIP() []byte {
	file_access_proto_rawDescOnce.Do(func() {
		file_access_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_access_proto_rawDesc), len(file_access_proto_rawDesc)))
	})
	return file_access_proto_rawDescData
}

var file_access_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_access_proto_goTypes = []any{
	(*Role)(nil),                  // 0: access.Role
	(*Permission)(nil),            // 1: access.Permission
	(*PermissionReq)(nil),         // 2: access.PermissionReq
	(*UpdateUserRoleReq)(nil),     // 3: access.UpdateUserRoleReq
	(*UserIDRoleName)(nil),        // 4: access.UserIDRoleName
	(*Roles)(nil),                 // 5: access.Roles
	(*Permissions)(nil),           // 6: access.Permissions
	(*FullPermissions)(nil),       // 7: access.FullPermissions
	(*UserID)(nil),                // 8: access.UserID
	(*RoleName)(nil),              // 9: access.RoleName
	(*Success)(nil),               // 10: access.Success
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
}
var file_access_proto_depIdxs = []int32{
	11, // 0: access.Role.created_at:type_name -> google.protobuf.Timestamp
	11, // 1: access.Role.updated_at:type_name -> google.protobuf.Timestamp
	11, // 2: access.Permission.created_at:type_name -> google.protobuf.Timestamp
	11, // 3: access.Permission.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 4: access.PermissionReq.Permission:type_name -> access.Permission
	0,  // 5: access.Roles.roles:type_name -> access.Role
	1,  // 6: access.Permissions.permissions:type_name -> access.Permission
	0,  // 7: access.AccessService.CreateRole:input_type -> access.Role
	8,  // 8: access.AccessService.GetRoles:input_type -> access.UserID
	2,  // 9: access.AccessService.CreatePermission:input_type -> access.PermissionReq
	8,  // 10: access.AccessService.GetFullPermission:input_type -> access.UserID
	8,  // 11: access.AccessService.GetPermissionsByUserID:input_type -> access.UserID
	9,  // 12: access.AccessService.GetPermissionsByRoleName:input_type -> access.RoleName
	4,  // 13: access.AccessService.AddUserRole:input_type -> access.UserIDRoleName
	8,  // 14: access.AccessService.BindUserRole:input_type -> access.UserID
	3,  // 15: access.AccessService.ReplaceUserRole:input_type -> access.UpdateUserRoleReq
	4,  // 16: access.AccessService.DeleteUserRole:input_type -> access.UserIDRoleName
	10, // 17: access.AccessService.CreateRole:output_type -> access.Success
	5,  // 18: access.AccessService.GetRoles:output_type -> access.Roles
	10, // 19: access.AccessService.CreatePermission:output_type -> access.Success
	7,  // 20: access.AccessService.GetFullPermission:output_type -> access.FullPermissions
	6,  // 21: access.AccessService.GetPermissionsByUserID:output_type -> access.Permissions
	6,  // 22: access.AccessService.GetPermissionsByRoleName:output_type -> access.Permissions
	10, // 23: access.AccessService.AddUserRole:output_type -> access.Success
	10, // 24: access.AccessService.BindUserRole:output_type -> access.Success
	10, // 25: access.AccessService.ReplaceUserRole:output_type -> access.Success
	10, // 26: access.AccessService.DeleteUserRole:output_type -> access.Success
	17, // [17:27] is the sub-list for method output_type
	7,  // [7:17] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_access_proto_init() }
func file_access_proto_init() {
	if File_access_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_access_proto_rawDesc), len(file_access_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_access_proto_goTypes,
		DependencyIndexes: file_access_proto_depIdxs,
		MessageInfos:      file_access_proto_msgTypes,
	}.Build()
	File_access_proto = out.File
	file_access_proto_goTypes = nil
	file_access_proto_depIdxs = nil
}
